#!/bin/bash

set -e

if [[ -n "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Format code with yapf
"
}

DIRS_TO_CHECK=("src" "tests" "scripts")

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # Code formatting
        yapf -irp --style='{based_on_style: pep8; column_limit: 100}' ${DIRS_TO_CHECK[@]}
    fi
fi
